### ISSUE TITLE
Why are there duplilcate messages?

### ISSUE THREAD

**Issue by maths644311798** [secretflow/interconnection#16]
Message "EcdhPsiCipherBatch" appears  in both /interconnection/interconnection/runtime/ecdh_psi.proto and /interconnection/interconnection/legacy/algos/psi.proto. Why does it appear twice in interconnection?

**Comment by usafchn** [comment]
Do not use the protos under `/interconnection/interconnection/legacy`, which stores outdated interfaces. Please ignore the 'legacy' dir

**Comment by maths644311798** [comment]
Why not just delete the diretory "legacy"?

**Comment by usafchn** [comment]
Some old systems and platforms still rely on legacy interfaces. If you are a new user, you don’t need to pay attention to the `legacy` dir
